name: Build and Assert Assets Exists
description: Build the package and assert that file contents exist as we expect
runs:
  using: "composite"
  steps:
  - name: Build and Assert Output
    shell: bash
    run: |-
      echo '
        target: ${{ env.dist }}
        setup:
          run: pnpm build:js
          cwd: ./ember-popperjs
        expect: |
          _app_/components/popper-j-s.js
          index.js
          index.js.map
          index.d.ts
          components/popper-j-s.js
          components/popper-j-s.js.map
          components/popper-j-s.d.ts
          components/popper-j-s.d.ts.map
          
      ' >> assert-contents.config.yml
      npx assert-folder-contents

  - name: Upload dist assets to cache
    uses: actions/upload-artifact@v4
    with:
      name: dist
      path: ${{ env.dist }}
  - name: 'Install dependencies'
    shell: 'bash'
    run: pnpm install
